# Generated by Django 3.1.1 on 2020-09-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200912_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enriched', models.BooleanField(default=False, verbose_name='Am I rich?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
