# Generated by Django 3.1.1 on 2020-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloguserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='blog.BlogUserProfile'),
        ),
    ]
