# Generated by Django 3.1.1 on 2020-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200912_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='bloguserprofile',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='blog.Post'),
        ),
    ]
