# Generated by Django 3.1.1 on 2020-09-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200912_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguserprofile',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='blog.BlogUserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.bloguserprofile'),
        ),
    ]
